# Generated by Django 6.0 on 2026-01-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='hub',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hub_images/'),
        ),
    ]
