# Generated by Django 6.0 on 2026-01-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_messagehighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_delete',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
